spring:
  datasource:
    url: jdbc:mysql://47.104.26.79:3306/bambootattan?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username : root
    password : 46132205092017
    driverClassName : com.mysql.cj.jdbc.Driver
---

spring:
  main:
    allow-bean-definition-overriding: true
---
#JPA Configuration:
spring :
  jpa:
    database : mysql
# Show or not log for each sql query
    show-sql : false
    generate-ddl : true
# Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto : update
#spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy : org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view : true
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
---

spring :
  data :
    redis:
      repositories:
        enabled: false
    elasticsearch :
      repositories :
        enabled : true
      cluster-name : elasticsearch
      cluster-nodes : 47.104.26.79:9300
---
logging :
  level:
    com :
      ahau : debug
    org:
      hibernate: info
  path: log/
---
spring:
  redis:
    database: 0
    host: 47.104.26.79
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 50
        min-idle: 0
        max-active: 50
        max-wait: -1ms
    timeout: 5000
---
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465
    username: 1172032260@qq.com
    password: kcrcbcsqwtouficd
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: false
            required: true
---
spring:
  #切面启用
  aop:
    proxy-target-class: true
    auto: true
